import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, Socket } from 'socket.io-client';
import './style.css';

type Player={x:number;y:number;a:number;turret:number;score:number}; type Wall={x:number;y:number;w:number;h:number}; type Bullet={x:number;y:number;owner:number};
type State={code:string;phase:string;players:Player[];walls:Wall[];bullets:Bullet[];winner?:number};
const W=1400,H=1000;
function draw(ctx:CanvasRenderingContext2D,s:State,slot:number){const c=ctx.canvas,scale=Math.min(c.width/W,c.height/H);ctx.setTransform(scale,0,0,scale,(c.width-W*scale)/2,(c.height-H*scale)/2);ctx.clearRect(0,0,W,H);ctx.fillStyle='#080b16';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#17274a';ctx.lineWidth=1;for(let x=0;x<W;x+=100){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=100){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#223456';ctx.shadowColor='#3266d4';ctx.shadowBlur=8;s.walls.forEach(w=>ctx.fillRect(w.x,w.y,w.w,w.h));ctx.shadowBlur=0;ctx.strokeStyle='#77a8ff';ctx.lineWidth=5;ctx.strokeRect(2,2,W-4,H-4);s.bullets.forEach(b=>{ctx.fillStyle=b.owner===0?'#17e6ff':'#ff3fb4';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=16;ctx.beginPath();ctx.arc(b.x,b.y,8,0,7);ctx.fill();ctx.shadowBlur=0});s.players.forEach((p,i)=>{const color=i===0?'#17e6ff':'#ff3fb4';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.shadowColor=color;ctx.shadowBlur=18;ctx.fillStyle=color;ctx.fillRect(-30,-24,60,48);ctx.fillStyle='#061328';ctx.beginPath();ctx.arc(0,0,15,0,7);ctx.fill();ctx.restore();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.turret??p.a);ctx.shadowColor=color;ctx.shadowBlur=14;ctx.fillStyle='#d9f9ff';ctx.fillRect(0,-7,58,14);ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,18,0,7);ctx.fill();ctx.restore()});}
function App(){const [socket,setSocket]=useState<Socket>();const [state,setState]=useState<State>();const [slot,setSlot]=useState<number>();const [code,setCode]=useState('');const [join,setJoin]=useState('');const [speed,setSpeed]=useState('normal');const [err,setErr]=useState('');const [drive,setDrive]=useState({x:0,y:0});const canvas=useRef<HTMLCanvasElement>(null);const controls=useRef({move:0,heading:0});const connectedToGame=useRef(false);const requestLandscape=()=>{const orientation=screen.orientation as unknown as {lock?: (mode:string)=>Promise<void>};void orientation.lock?.('landscape').catch(()=>undefined)};
 useEffect(()=>{const s=io();setSocket(s);s.on('room-joined',(d:{code:string;slot:number;state:State})=>{setCode(d.code);setSlot(d.slot);setState(d.state);setErr('')});s.on('game-state',setState);s.on('round-result',setState);s.on('match-result',setState);s.on('player-disconnected',()=>setErr('Rakibin bağlantısı kesildi. Oda kısa süre içinde kapanacak.'));s.on('room-error',setErr);return()=>{s.close()}},[]);
 connectedToGame.current=Boolean(state&&slot!==undefined);
 useEffect(()=>{if(!socket||slot===undefined||!code)return;const id=setInterval(()=>{if(connectedToGame.current)socket.emit('player-input',{code,input:controls.current})},1000/60);return()=>clearInterval(id)},[slot,socket,code]);
 useEffect(()=>{const c=canvas.current;if(!c||!state||slot===undefined)return;const ctx=c.getContext('2d')!;const resize=()=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;draw(ctx,state,slot)};resize();window.addEventListener('resize',resize);draw(ctx,state,slot);return()=>window.removeEventListener('resize',resize)},[state,slot]);
 const share=async()=>{const text=`Neon Tank Düellosu odama katıl: ${code}`;if(navigator.share)await navigator.share({title:'Neon Tank Düellosu',text});else await navigator.clipboard.writeText(code)};
 const pointer=(e:React.PointerEvent<HTMLDivElement>)=>{const box=e.currentTarget.getBoundingClientRect(),rawX=(e.clientX-box.left)/box.width-.5,rawY=(e.clientY-box.top)/box.height-.5,len=Math.hypot(rawX,rawY),scale=len>.5?.5/len:1,x=rawX*scale,y=rawY*scale;const power=Math.min(1,Math.hypot(x,y)*2);controls.current={move:power,heading:power>.05?Math.atan2(y,x):controls.current.heading};setDrive({x:x*2,y:y*2})};
 const release=()=>{controls.current={...controls.current,move:0};setDrive({x:0,y:0})};
 if(!state)return <main className="lobby"><div className="brand">NEON<br/><b>TANK DUEL</b></div><p>İki telefon. Tek arena. Son tank ayakta kalır.</p><label className="speed">TANK HIZI<select value={speed} onChange={e=>setSpeed(e.target.value)}><option value="slow">Yavaş</option><option value="normal">Normal</option><option value="fast">Hızlı</option></select></label><button onClick={()=>{requestLandscape();socket?.emit('create-room',{speed})}}>ODA OLUŞTUR</button><div className="or">veya</div><input value={join} onChange={e=>setJoin(e.target.value.toUpperCase())} maxLength={4} placeholder="ODA KODU"/><button className="secondary" onClick={()=>{requestLandscape();socket?.emit('join-room',join)}}>KATIL</button>{err&&<small>{err}</small>}</main>;
 const leave=()=>{socket?.emit('leave-room',{code});setState(undefined);setSlot(undefined);setCode('');setErr('')};const headline=state.phase==='waiting'?'Rakip bekleniyor…':state.phase==='result'?`${state.winner===slot?'ELİ KAZANDIN!':'RAKİBİN KAZANDI'}`:state.phase==='match-over'?`${state.winner===slot?'MAÇ SENİN!':'MAÇ BİTTİ'}`:'HEDEFİ YOK ET';return <main className="game"><header><button className="menu" onClick={leave}>MENÜ</button><strong>{headline}</strong><span className="score"><i>{state.players[slot!]?.score??0}</i> — {state.players[slot===0?1:0]?.score??0}</span></header><canvas ref={canvas}/>{state.phase==='waiting'&&<section className="invite"><b>Oda kodun: {code}</b><button onClick={share}>DAVETİ PAYLAŞ</button></section>}<section className="controls"><div className="stick move" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointer(e)}} onPointerMove={pointer} onPointerUp={release} onPointerCancel={release}><span className="knob" style={{transform:`translate(${drive.x*32}px,${drive.y*32}px)`}}>SÜR</span></div><button className="fire" onClick={()=>socket?.emit('fire',{code})}>ATEŞ</button></section>{err&&<small>{err}</small>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
