import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, Socket } from 'socket.io-client';
import './style.css';

type Player={x:number;y:number;a:number;score:number}; type Wall={x:number;y:number;w:number;h:number}; type Bullet={x:number;y:number;owner:number};
type State={code:string;phase:string;players:Player[];walls:Wall[];bullets:Bullet[];winner?:number};
const W=1400,H=1000;
function draw(ctx:CanvasRenderingContext2D,s:State,slot:number){const c=ctx.canvas,scale=Math.min(c.width/W,c.height/H);ctx.setTransform(scale,0,0,scale,(c.width-W*scale)/2,(c.height-H*scale)/2);ctx.clearRect(0,0,W,H);ctx.fillStyle='#050816';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#11254b';ctx.lineWidth=2;for(let x=0;x<W;x+=100){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=100){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#17264b';ctx.shadowColor='#3266d4';ctx.shadowBlur=12;s.walls.forEach(w=>{ctx.fillRect(w.x,w.y,w.w,w.h);ctx.strokeStyle='#4a71c8';ctx.strokeRect(w.x,w.y,w.w,w.h)});ctx.shadowBlur=0;s.bullets.forEach(b=>{ctx.fillStyle=b.owner===0?'#17e6ff':'#ff3fb4';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=16;ctx.beginPath();ctx.arc(b.x,b.y,8,0,7);ctx.fill();ctx.shadowBlur=0});s.players.forEach((p,i)=>{const color=i===0?'#17e6ff':'#ff3fb4';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.shadowColor=color;ctx.shadowBlur=18;ctx.fillStyle=color;ctx.fillRect(-30,-24,60,48);ctx.fillStyle='#d9f9ff';ctx.fillRect(0,-7,50,14);ctx.fillStyle='#061328';ctx.beginPath();ctx.arc(0,0,15,0,7);ctx.fill();ctx.restore()});}
function App(){const [socket,setSocket]=useState<Socket>();const [state,setState]=useState<State>();const [slot,setSlot]=useState<number>();const [code,setCode]=useState('');const [join,setJoin]=useState('');const [err,setErr]=useState('');const canvas=useRef<HTMLCanvasElement>(null);const controls=useRef({move:0,turn:0});const aim=useRef(0);
 useEffect(()=>{const s=io();setSocket(s);s.on('room-joined',(d:{code:string;slot:number;state:State})=>{setCode(d.code);setSlot(d.slot);setState(d.state);setErr('')});s.on('game-state',setState);s.on('round-result',setState);s.on('match-result',setState);s.on('player-disconnected',()=>setErr('Rakibin bağlantısı kesildi. Oda kısa süre içinde kapanacak.'));s.on('room-error',setErr);return()=>{s.close()}},[]);
 useEffect(()=>{if(!state||slot===undefined||!socket)return;const id=setInterval(()=>socket.emit('player-input',{code,input:controls.current}),33);return()=>clearInterval(id)},[state,slot,socket,code]);
 useEffect(()=>{const c=canvas.current;if(!c||!state||slot===undefined)return;const ctx=c.getContext('2d')!;const resize=()=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;draw(ctx,state,slot)};resize();window.addEventListener('resize',resize);draw(ctx,state,slot);return()=>window.removeEventListener('resize',resize)},[state,slot]);
 const share=async()=>{const text=`Neon Tank Düellosu odama katıl: ${code}`;if(navigator.share)await navigator.share({title:'Neon Tank Düellosu',text});else await navigator.clipboard.writeText(code)};
 const pointer=(side:'move'|'aim',e:React.PointerEvent<HTMLDivElement>)=>{const box=e.currentTarget.getBoundingClientRect(),x=(e.clientX-box.left)/box.width-.5,y=(e.clientY-box.top)/box.height-.5;if(side==='move'){controls.current={move:Math.max(-1,Math.min(1,-y*2)),turn:Math.max(-1,Math.min(1,x*2))}}else if(x*x+y*y>.02)aim.current=Math.atan2(y,x)};
 const release=(side:'move'|'aim')=>{if(side==='move')controls.current={move:0,turn:0};else if(socket&&state&&slot!==undefined)socket.emit('fire',{code,angle:aim.current})};
 if(!state)return <main className="lobby"><div className="brand">NEON<br/><b>TANK DUEL</b></div><p>İki telefon. Tek arena. Son tank ayakta kalır.</p><button onClick={()=>socket?.emit('create-room')}>ODA OLUŞTUR</button><div className="or">veya</div><input value={join} onChange={e=>setJoin(e.target.value.toUpperCase())} maxLength={4} placeholder="ODA KODU"/><button className="secondary" onClick={()=>socket?.emit('join-room',join)}>KATIL</button>{err&&<small>{err}</small>}</main>;
 const headline=state.phase==='waiting'?'Rakip bekleniyor…':state.phase==='result'?`${state.winner===slot?'ELİ KAZANDIN!':'RAKİBİN KAZANDI'}`:state.phase==='match-over'?`${state.winner===slot?'MAÇ SENİN!':'MAÇ BİTTİ'}`:'HEDEFİ YOK ET';return <main className="game"><div className="rotate-hint">↻<b>Telefonunu yatay çevir</b><span>Tank düellosu yatay ekranda oynanır.</span></div><header><span className="code">ODA {code}</span><strong>{headline}</strong><span className="score"><i>{state.players[slot!]?.score??0}</i> — {state.players[slot===0?1:0]?.score??0}</span></header><canvas ref={canvas}/>{state.phase==='waiting'&&<section className="invite"><b>Oda kodun: {code}</b><button onClick={share}>DAVETİ PAYLAŞ</button></section>}<section className="controls"><div className="stick move" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointer('move',e)}} onPointerMove={e=>pointer('move',e)} onPointerUp={()=>release('move')}>SÜR</div><div className="stick aim" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointer('aim',e)}} onPointerUp={()=>release('aim')}>NİŞAN<br/>ATEŞ</div></section>{err&&<small>{err}</small>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
